// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModeUpdateRequest mode update request
//
// swagger:model ModeUpdateRequest
type ModeUpdateRequest struct {

	// mode
	Mode string `json:"mode,omitempty"`
}

// Validate validates this mode update request
func (m *ModeUpdateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this mode update request based on context it is used
func (m *ModeUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModeUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModeUpdateRequest) UnmarshalBinary(b []byte) error {
	var res ModeUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
